config/routes.rb
Blog::Application.routes.draw do

  root :to => "posts#index"
  match 'about' => "application#about"

  resources :posts do 
    resources :comments
  end
    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => TRUE, :length => { :minimum => 5 }
  validates :body, :presence => TRUE
  has_many :comments, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def logged?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params[:comment])

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    @post.comments = Comment.where("post_id" => (params[:id]))
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper

# Funktion zur Überprüfung, ob ein User angemeldet ist
def logged_in?
  not session[:user_id].nil?
end

# Diese Funktion gibt ein Datum in der deutschen TAG.MONAT.JAHR Schreibweise zurück
def german_date(time)
  if time != nil 
  time.strftime("%d.%m.%Y")
  else
    ("unknown!")
  end
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :combody %><br />
    <%= f.text_area :combody %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Combody</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post_id %></td>
    <td><%= comment.combody %></td>
    <td><%= comment.author %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>Combody:</b>
  <%= @comment.combody %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KS&nbsp;Web&nbsp;Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="topline">
  <p>
   <br />
   <h1>KS&nbsp;WebDesign&nbsp;spaces</h1>
  </p>
 </div>
   <div id="submenu">
     <ul>
	<li><%= link_to "new post", new_post_path %></li>
	<li><%= link_to "blog", posts_path %></li>
	<li><%= link_to "about", about_path %></li>
     </ul>
     <ul style="margin-lefit:20%">
       <li><%= link_to "login", new_post_path %></li>
       <li><%= link_to "register", new_post_path %></li>
     </ul>
   </div>

<div id="sidemenu">
  some text to fill later with useful stuff!!

<div id="container">
  <br />
  <div id="header"> 
    <h1>KS WebDesign</h1>   
  </div>

   <div id="content">
     <%= yield %>
   </div>

   <div id="footer">
     TODO - Finally some kind of copyright and author information will appear HERE !!
   </div>
 </div>

</div>
  
<div style="clear:both">
</div>

  <div id="footbar">
     <h1>Place for Impressum, Kontakt, eMail etc.</h1>
  
</div>

  </body>
</html>

app/views/posts/_comment.html.erb
<hr />
<%= div_for comment do %>
<p style="font-size:0.9em">
  <strong>Posted <%= time_ago_in_words(comment.created_at) %>
    ago</strong></p>
       <p>
	 <%= h(comment.combody) %>
	 <hr />
	 </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => "8", :columns => "25" %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.date_select :published_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>
<div id="control">
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>KS Webs blog</h1>

<table id="indx">
<% @posts.reverse.each do |post| %>
  <tr style="border-bottom:1px solid #D3D3D3">
    <td>
      <h2><%= link_to post.title, post %></h2>
      <i><b>Published on:</b> <%= german_date(post.published_on) %> <b>Author:</b> <%= post.author %></i><br />
      <p>
	<%= post.body %>
	</p>
     </td> 
   <% if logged_in? %>
    <td class="controls"><%= link_to 'Edit', edit_post_path(post) %><br />
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
    <% else %>
    <td class="controls"><%= link_to 'Edit', edit_post_path(post) %><br />
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
 </tr>
<% end %>
</table>
<br />

<div id="control">
<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
<div id="control">
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<h2>
   <%= @post.title %>
</h2>
<p>
  <i><b>Published on:</b>
  <%= german_date(@post.published_on) %>&nbsp;&nbsp;
  <b>Author:</b>
  <%= @post.author %></i>
</p>
<p>
   <%= @post.body %>
</p>

  <div id="control">
    <%= link_to 'Edit', edit_post_path(@post) %>&nbsp;|
    <%= link_to 'Back', posts_path %>
  </div>
</div>